#!/usr/bin/env sh

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec java \
  -Dsbt.supershell=false \
  -Dsbt.log.noformat=true \
  -jar "$script_dir/project/sbt-launch.jar" \
  "$@"
